# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 05:59
from __future__ import unicode_literals

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Posts.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
    ]
