# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-update'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
