# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 22, 48, 24, 75293, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
